<a href="https://colab.research.google.com/github/Supu12-ui/DataScience/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install numpy

In [ ]:
import numpy as np
import time
import sys

In [ ]:
size=100
l1 = range(size)
l2=range(size)
a1=np.arange(size)
a2=np.arange(size)


In [ ]:
#numpy is faster than as python 
l1 = [1,2,3,4]
l2  = [5,6,7]
start=time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list ",(time.time()-start)*1000)
start=time.time()
a1=np.array([2,3,4,5,6,6,4,5,6,4,5,6,7,8,6,3,4,5,6,7,5,5])
a2=np.array([4,5,6,67,89,675,45,643,2,4,5,66,7,5,4,4,6,7,6,7,9,67])
result=a1+a2
print("Numpy list",(time.time() -start)*1000)
    



python list  0.0
Numpy list 0.0


In [ ]:
a = np.array([1,2,3]) #to get array in 1 d
print(a)

[1 2 3]


In [ ]:
a = np.array([[1,2,3],[3,4,5],[6,7,8]]) #to get array in 2D
print(a)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [ ]:
a.ndim #for getting the dimension

2

In [ ]:
a.itemsize #for getting the bit size 

4

In [ ]:
a.dtype

dtype('int32')

In [ ]:
a=np.array([[2,3,4],[4,5,6],[7,8,9]],dtype=np.float64)
a.itemsize


8

In [ ]:
a.dtype

dtype('float64')

In [ ]:
print(a)

[[2. 3. 4.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
a.size

9

In [ ]:
a.shape

(3, 3)

In [ ]:
a1=np.zeros((3,3))
a1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a1=np.ones((3,4))
a1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
l=range(0,5)
l

range(0, 5)

In [ ]:
a=np.arange(0,5)
a

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(1,5,2)

array([1, 3])

In [ ]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [ ]:
a=np.array([[1,2,3,4],[6,7,8,5],[8,9,1,2]])
a.reshape(3,4)
a.reshape(12,1)


array([[1],
       [2],
       [3],
       [4],
       [6],
       [7],
       [8],
       [5],
       [8],
       [9],
       [1],
       [2]])

In [ ]:
a.ravel()

array([1, 2, 3, 4, 6, 7, 8, 5, 8, 9, 1, 2])

In [ ]:
a=np.array([1,2,3,4,576,6,64])
a.min() #for getting the minimum value

1

In [ ]:
a=np.array([3,4,5,6,4,6,7])
a.max() #for getting the maximum value

7

In [ ]:
a.sum() #it will sum up the all element

35

In [ ]:
a=np.array([[2,3,4],[6,7,8],[8,8,4]])
a.sum() #it will sum up all the row as well as column

50

In [ ]:
a.sum(axis=0) #it will sum up only row wise because we had taken axis=0

array([16, 18, 16])

In [ ]:
a.sum(axis=1)#it will take all the column sum because we took the axis=1

array([ 9, 21, 20])

In [ ]:
np.sqrt(a) #square root of every element

array([[1.41421356, 1.73205081, 2.        ],
       [2.44948974, 2.64575131, 2.82842712],
       [2.82842712, 2.82842712, 2.        ]])

In [ ]:
np.std(a) #it will give the deviation

2.2166597048066667

In [ ]:
a=np.array([[2,3,4],[6,7,8],[8,8,4]])
b=np.array([[2,4,5],[7,8,5],[6,7,5]])
a


array([[2, 3, 4],
       [6, 7, 8],
       [8, 8, 4]])

In [ ]:
b

array([[2, 4, 5],
       [7, 8, 5],
       [6, 7, 5]])

In [ ]:
a+b


array([[ 4,  7,  9],
       [13, 15, 13],
       [14, 15,  9]])

In [ ]:
a*b

array([[ 4, 12, 20],
       [42, 56, 40],
       [48, 56, 20]])

In [ ]:
a-b

array([[ 0, -1, -1],
       [-1, -1,  3],
       [ 2,  1, -1]])

In [ ]:
a/b

array([[1.        , 0.75      , 0.8       ],
       [0.85714286, 0.875     , 1.6       ],
       [1.33333333, 1.14285714, 0.8       ]])

In [ ]:
a.dot(b)

array([[ 49,  60,  45],
       [109, 136, 105],
       [ 96, 124, 100]])

# Indexing and slicing 

In [ ]:
n = [6,7,8]
n[0:2]

[6, 7]

In [ ]:
n[-1]

8

In [ ]:
a = np.array([6,7,8])
a[0:2]

array([6, 7])

In [ ]:
a[-1]

8

In [ ]:
a=np.array([[1,2,3,4],[6,7,8,5],[8,9,1,2]])
a[2,3]

2

In [ ]:
a

array([[1, 2, 3, 4],
       [6, 7, 8, 5],
       [8, 9, 1, 2]])

In [ ]:
a[0:3,2]

array([3, 8, 1])

In [ ]:
a[-1]

array([8, 9, 1, 2])

In [ ]:
a[-1,0:4]

array([8, 9, 1, 2])

In [ ]:
a[:,1:4]

array([[2, 3, 4],
       [7, 8, 5],
       [9, 1, 2]])

#iteration in an array 

In [ ]:
for row in a:
    print(row)

[1 2 3 4]
[6 7 8 5]
[8 9 1 2]


In [ ]:
for row in a.flat:
    print(row)

1
2
3
4
6
7
8
5
8
9
1
2


# Stacking together an array 

In [ ]:
a = np.array(np.arange(6,12).reshape(3,2))
a

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
b = np.array(np.arange(11,17).reshape(3,2))
b

array([[11, 12],
       [13, 14],
       [15, 16]])

In [ ]:
np.vstack((a,b))

array([[ 6,  7],
       [ 8,  9],
       [10, 11],
       [11, 12],
       [13, 14],
       [15, 16]])

In [ ]:
c = np.array(np.arange(30).reshape(2,15))
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
np.hsplit(c,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [ ]:
result =np.hsplit(c,3)
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [ ]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [ ]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [ ]:
result=np.vsplit(c,2)
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [ ]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
b = a>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
a[b] #it return the index which is true 

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
a[b]=-1 # where there is equal to true than it will give -1
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

# itertrate numpy arrat using nditor


In [ ]:
a = np.array(np.arange(12).reshape(3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
for row in a:
    for col in row:
        print(col)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for row in a.flat:
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for row in np.nditer(a,order='C'):
    print(row)

0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
for row in np.nditer(a,order='F'):
    print(row)

0
4
8
1
5
9
2
6
10
3
7
11


In [ ]:
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [ ]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]=x*x

In [ ]:
x

array(121)